[versions]
appVersion = "1.0.1"
java = "21"

androidGradlePlugin = "9.2.0-alpha03"

kotlin = "2.3.10"
kotlinCoroutines = "1.10.2"
kotlinxAtomicfu = "0.31.0"
kotlinxDatetime = "0.7.1"
bigDecimal = "0.3.10"
kmpIo = "0.3.0"
vannikTech = "0.36.0"

sqlcipher = "4.12.0"
openssl = "3.6.0"
sqlcipherBuildPlugin = "0.5.3"

androidBuildTools = "36.1.0"
androidSdk = "36"
# Use 26 for publishing. To avoid JUnit5/6 desugaring issues, use 35 for androidDeviceTest builds/tests
androidSdkMinimum = "26"
#androidSdkMinimum = "35"
androidNdk = "29.0.14206865"
cmake = "4.1.2"

iosMinSdk = "14"

dokkaPlugin = "2.1.0"
jupiter = "6.0.3"
testMannodermausPlugin = "2.0.1"
androidxTestRunner = "1.7.0"
versionCheck = "0.53.0"
appcompat = "1.7.1"
material = "1.13.0"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinxAtomicfu"}
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime"}
bigDecimal = { module = "com.ionspin.kotlin:bignum", version.ref = "bigDecimal"}
kmp-io = { module = "io.github.skolson:kmp-io", version.ref = "kmpIo"}
kmp-sqlencrypt-jni-android = { module = "io.github.skolson:kmp-android-jni", version.ref = "appVersion"}


#testing libraries
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines"}
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter" }
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }
android-jupiter-test-runner = { module = "de.mannodermaus.junit5:android-test-runner", version.ref = "testMannodermausPlugin" }
android-jupiter-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "jupiter" }
android-jupiter-suite-api = { module = "org.junit.platform:junit-platform-suite-api", version.ref = "jupiter" }

[bundles]
androidx-test = [ "kotlinx-coroutines-test", "kotlinx-coroutines-core", "jupiter-api", "jupiter-params", "jupiter-engine", "androidx-test-runner", "android-jupiter-test-runner", "android-jupiter-launcher", "android-jupiter-suite-api" ]

[plugins]
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }
maven-publish-vannik = { id = "com.vanniktech.maven.publish", version.ref = "vannikTech" }
sqlcipher-build = { id = "com.oldguy.gradle.sqlcipher-openssl-build", version.ref = "sqlcipherBuildPlugin" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }

android-jupiter = { id = "de.mannodermaus.android-junit5", version.ref = "testMannodermausPlugin"}
dokka = { id = "org.jetbrains.dokka", version.ref = "dokkaPlugin" }
versionCheck = { id = "com.github.ben-manes.versions", version.ref = "versionCheck" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
