package com.oldguy.kiscmp

import com.oldguy.kiscmp.SqliteDatabase.Companion.translate
import com.oldguy.sqlcipher.android.Sqlite3JniShim
import com.oldguy.sqlcipher.android.Sqlite3StatementJniShim

/**
 * Android implementation is this wrapper around the native sqlite3 library using Sqlite3JniShim.
 * Due to Google forcing the JNI code to a separate module, the main module can no longer share
 * its SqliteException definition. So this wrapper has to translate the JNI-specific SqliteException
 * instance to the common Kotlin SqliteException instance.
 *
 */
actual class SqliteDatabase {
    internal val shim = Sqlite3JniShim()
    actual var encoding = SqliteEncoding.Utf8
    actual val notDatabaseResult = 26 // must match SQLITE_NOTADB value in sqlite3.h

    actual fun error(): String {
        return shim.error()
    }

    actual fun fileName(): String {
        return shim.fileName()
    }

    actual fun open(
        path: String,
        readOnly: Boolean,
        createOk: Boolean
    ): Int {
        try {
            return shim.open(path, readOnly, createOk)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun close(): Int {
        try {
            return shim.close()
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun softHeapLimit(limit: Long): Long {
        return shim.softHeapLimit(limit)
    }

    actual fun busyTimeout(timeout: Int) {
        return shim.busyTimeout(timeout)
    }

    actual fun exec(
        sql: String,
        callback: ((values: Array<String>, columnNames: Array<String>) -> Int)?
    ): Int {
        try {
            return callback?.let {
                shim.exec(sql, it)
            } ?: shim.exec(sql)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun exec(sql: String): Int {
        try {
            return shim.exec(sql)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun version(): String {
        return shim.version()
    }

    /**
     * Useful after an Insert statement when a ROWID is expected to be generated by Sqlite during
     * the insert
     */
    actual fun lastInsertRowid(): Long {
        try {
            return shim.lastInsertRowid()
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun sleep(millis: Int) {
        shim.sleep(millis)
    }

    companion object {
        fun translate(e: com.oldguy.sqlcipher.android.SqliteException): SqliteException {
            return SqliteException(e.msg, e.apiName, e.result)
        }
    }
}

/**
 * Android implementation is this wrapper around the native sqlite3 library using Sqlite3JniShim.
 * As with the database implementation, SqliteException translation has to happen here as well.
 */
actual class SqliteStatement actual constructor(val db: SqliteDatabase) {
    private val shim = Sqlite3StatementJniShim()

    actual fun parameterCount(): Int {
        try {
            return shim.parameterCount()
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun isReadOnly(): Boolean {
        return shim.isReadOnly()
    }

    actual fun prepare(sql: String): Int {
        try {
            return shim.prepare(db.shim.handle, sql)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun bindIndex(name: String): Int {
        try {
            return shim.bindIndex(name)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun bindNull(index: Int): Int {
        try {
            return shim.bindNull(index)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun bindText(index: Int, text: String): Int {
        try {
            return shim.bindText(index, text)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun bindInt(index: Int, value: Int): Int {
        try {
            return shim.bindInt(index, value)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun bindLong(index: Int, value: Long): Int {
        try {
            return shim.bindLong(index, value)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun bindDouble(index: Int, value: Double): Int {
        try {
            return shim.bindDouble(index, value)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun bindBytes(index: Int, array: ByteArray): Int {
        try {
            return shim.bindBytes(index, array)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun step(): SqliteStepResult {
        try {
            return when (val rc = shim.stepInt()) {
                1 -> SqliteStepResult.Error
                2 -> SqliteStepResult.Done
                3 -> SqliteStepResult.Row
                4 -> SqliteStepResult.Busy
                else -> throw SqliteException("Unsupported return from StepInt(): $rc")
            }
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun changes(): Int {
        try {
            return shim.changes(db.shim.handle)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun finalize(): Int {
        try {
            return shim.finalize()
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun clearBindings() {
        shim.clearBindings()
    }

    actual fun reset() {
        shim.reset()
    }

    /**
     * The following functions are only useful when preparing and running a select statement.
     */
    actual fun expandedSql(): String {
        try {
            return shim.expandedSql()
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun isBusy(): Boolean {
        return shim.isBusy()
    }

    actual fun columnCount(): Int {
        return shim.columnCount()
    }

    actual fun dataCount(): Int {
        return shim.dataCount()
    }

    actual fun columnName(index: Int): String {
        try {
            return shim.columnName(index)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun columnDeclaredType(index: Int): String {
        try {
            return shim.columnDeclaredType(index)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun columnType(index: Int): SqliteColumnType {
        try {
            return when (val rc = shim.columnTypeInt(index)) {
                1 -> SqliteColumnType.Null
                2 -> SqliteColumnType.Text
                3 -> SqliteColumnType.Integer
                4 -> SqliteColumnType.Float
                5 -> SqliteColumnType.Blob
                else -> throw SqliteException("Unsupported return from columnTypeInt($index): $rc")
            }
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun columnText(index: Int): String {
        try {
            return shim.columnText(index)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun columnBlob(index: Int): ByteArray {
        try {
            return shim.columnBlob(index)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun columnDouble(index: Int): Double {
        try {
            return shim.columnDouble(index)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun columnInt(index: Int): Int {
        try {
            return shim.columnInt(index)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }

    actual fun columnLong(index: Int): Long {
        try {
            return shim.columnLong(index)
        } catch (e: com.oldguy.sqlcipher.android.SqliteException) {
            throw translate(e)
        }
    }
}