package com.oldguy.kiscmp

actual class SqliteDatabase {
    actual fun error(): String {
        TODO("Not yet implemented")
    }

    actual fun fileName(): String {
        TODO("Not yet implemented")
    }

    actual fun open(
        path: String,
        readOnly: Boolean,
        createOk: Boolean
    ): Int {
        TODO("Not yet implemented")
    }

    actual fun close(): Int {
        TODO("Not yet implemented")
    }

    actual fun softHeapLimit(limit: Long): Long {
        TODO("Not yet implemented")
    }

    actual fun busyTimeout(timeout: Int) {
    }

    actual fun exec(
        sql: String,
        callback: ((numberColumns: Int, values: Array<String>, columnNames: Array<String>) -> Int)?
    ): Int {
        TODO("Not yet implemented")
    }

    actual fun version(): String {
        TODO("Not yet implemented")
    }

    /**
     * Useful after an Insert statement when a ROWID is expected to be generated by Sqlite during
     * the insert
     */
    actual fun lastInsertRowid(): Long {
        TODO("Not yet implemented")
    }

    actual fun sleep(millis: Int) {
    }

}

actual class SqliteStatement actual constructor(val db: SqliteDatabase) {
    actual fun parameterCount(): Int {
        TODO("Not yet implemented")
    }

    actual fun isReadOnly(): Boolean {
        TODO("Not yet implemented")
    }

    actual fun prepare(sql: String): Int {
        TODO("Not yet implemented")
    }

    actual fun bindIndex(name: String): Int {
        TODO("Not yet implemented")
    }

    actual fun bindNull(index: Int): Int {
        TODO("Not yet implemented")
    }

    actual fun bindText(index: Int, text: String): Int {
        TODO("Not yet implemented")
    }

    actual fun bindInt(index: Int, value: Int): Int {
        TODO("Not yet implemented")
    }

    actual fun bindLong(index: Int, value: Long): Int {
        TODO("Not yet implemented")
    }

    actual fun bindDouble(index: Int, value: Double): Int {
        TODO("Not yet implemented")
    }

    actual fun bindBytes(index: Int, array: ByteArray): Int {
        TODO("Not yet implemented")
    }

    actual enum class StepResult {
        Done, Row, Busy, Error
    }

    actual fun step(): StepResult {
        TODO("Not yet implemented")
    }

    actual fun changes(): Int {
        TODO("Not yet implemented")
    }

    actual fun finalize(): Int {
        TODO("Not yet implemented")
    }

    actual fun clearBindings() {
    }

    actual fun reset() {
    }

    /**
     * The following functions are only useful when preparing and running a select statement.
     */
    actual fun expandedSql(): String {
        TODO("Not yet implemented")
    }

    actual fun isBusy(): Boolean {
        TODO("Not yet implemented")
    }

    actual fun columnCount(): Int {
        TODO("Not yet implemented")
    }

    actual fun dataCount(): Int {
        TODO("Not yet implemented")
    }

    actual fun columnName(index: Int): String {
        TODO("Not yet implemented")
    }

    actual fun columnDeclaredType(index: Int): String {
        TODO("Not yet implemented")
    }

    actual enum class ColumnType {
        Null, Integer, Text, Float, Blob
    }

    actual fun columnType(index: Int): ColumnType {
        TODO("Not yet implemented")
    }

    actual fun columnText(index: Int): String {
        TODO("Not yet implemented")
    }

    actual fun columnBlob(index: Int): ByteArray {
        TODO("Not yet implemented")
    }

    actual fun columnDouble(index: Int): Double {
        TODO("Not yet implemented")
    }

    actual fun columnInt(index: Int): Int {
        TODO("Not yet implemented")
    }

    actual fun columnLong(index: Int): Long {
        TODO("Not yet implemented")
    }

}